# DEV

services:
  db:
    image: postgres:15
    container_name: mindfulBot-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: "Europe/Moscow"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro  # Монтируем временную зону с хоста
      - /usr/share/zoneinfo/Europe/Moscow:/etc/timezone:ro # Монтируем информацию о временной зоне
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  postgres_data: